### ISSUE TITLE
Book on multiple shelves.

### ISSUE THREAD

**Issue by cthulahoops** [mouse-reeve/bookwyrm#115]
If you import a book you already have shelved but with a different state in the import, then the book gets added to a second shelf, and the book page crashes when you try to view it.

What's the expected behaviour here? Can a user have a book on multiple shelves. Can we enforce this constraint in the database?

I think the core shelves are exclusive, but additional user created shelves are not (optionally not?). It might be possible to enforce this in the db. When a user imports an already present book, I don't think we should reshelve the book. (Assume the data we have is more up to date than the import? I may be biased because this happened to me because of newer data in fedireads.)

**Comment by mouse-reeve** [comment]
A book should be able to be on multiple shelves, I think. If you were re-reading a book, for example, it should be able to exist as both read and currently reading. 

I think it might make sense for a ShelfBook entry to behave more like a "book instance" shelf than just a through table, and store reading progress and start/finished dates. 

The templates definitely need reworking to accommodate that

**Comment by cthulahoops** [comment]
Re-reading a book is exactly the case I ran into.

I think "reading activity" should probably be separate from shelves. Custom shelves probably don't relate to progress/start/finish dates in a way that makes sense. It's also going to get very confusing for the shelf metaphor/ui if a book you've read multiple times ends up on your read shelf multiple times (how would would we represent this?)

I would expect a separate ReadingActivity table tracking start/finish dates, and shelves which may or may not be exclusive.

(I'm modelling this on my understanding of how goodreads does it, which may not be right for us, but does make sense to me.)

**Comment by cthulahoops** [comment]
Linking related bugs: #73, #77

**Comment by mouse-reeve** [comment]
you're right - it would also create a weird case if you read a book and then un-shelved it (it shouldn't delete your reading history)
