### ISSUE TITLE
clarify home/local/federated concepts in UI

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#145]
I don't know exactly how to do this, but I think just having those words in tabs is pretty ??? for users who aren't already on mastodon or used to the federation model. maybe there could be some kind of blub/tooltip/idk to concisely explain what these are?

**Comment by luvicsoura** [comment]
I think a tutorial guiding the user through these tabs and the concepts of what they do/mean would be a a great complement to the blub/tooltip.

**Comment by mouse-reeve** [comment]
yeah! I think that's a good idea too
