### ISSUE TITLE
Login edit fields are missing labels.

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#180]
I couldn't tell if this was a problem on just the demo website or the whole program, but if it is an issue with the whole program, then this is a bug!

If it's only happening on the demo site, I wouldn't worry that much about it, but when using NVDA, The sign up edit fields are all labeled properly, but the login edit fields are not labeled properly. It looks like the label isn't attached to the corresponding field.

If this fix could be applied to the core, that would be best, since, all future Instances would be accessible.

**Comment by mouse-reeve** [comment]
oh, I think I know why this is happening -- both forms are generated by django and share some of the same fields. As a result, it's generating duplicate labels that don't correctly get assigned to their input fields.

I'll have to investigate how best to fix this. Thanks for the report!
