### ISSUE TITLE
book_cover.html template: 'NoneType' object has no attribute 'physical_format' 

### ISSUE THREAD

**Issue by bdelanghe** [mouse-reeve/bookwyrm#184]
After creating an account page failed to load. It looks like there is a None object in the books database which caused the code to break on line 9.

```html
1 | {% load fr_display %}
-- | --
{% if book.cover %}
<img class="book-cover {{ size }}" src="/images/{{ book.cover }}" alt="{% include 'snippets/cover_alt.html' with book=book %}">
{% else %}
<div class="no-cover book-cover {{ size }}">
<img class="book-cover {{ size }}" src="/static/images/no_cover.jpg" alt="No cover">
<div>
<p class="title">{{ book.title }}</p>
<p>({{ book\|edition_info }})</p>
</div>
</div>
{% endif %}
```

**Comment by mouse-reeve** [comment]
the error here is, I think, in the template for the cover image alt text (`fedireads/templates/snippets/cover_alt.html`)

**Comment by mouse-reeve** [comment]
Apparently I already fixed this in May! It probably has not been fixed in the demo, which has gotten too out of date to maintain.
