### ISSUE TITLE
Completing re-name from fedireads to BookWyrm

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#188]
this is overdue! My plan, starting today or this weekend

- [x] Rename the github repo
- [x] Update readme/documentation to reflect the change
- Re-name the software internally 
  - [ ] filenames (like the connector)
  - [ ] variable names
  - [ ] the "software" name that gets federated in the instance description)

@cthulahoops @loganmhb @rkingett, you are the people I know of who have been involved lately. Does this pose any problems for you that I can mitigate?

**Comment by loganmhb** [comment]
Shouldn't be a problem for me, thanks for checking!
