### ISSUE TITLE
Add some links to example instances in the readme

### ISSUE THREAD

**Issue by amcewen** [mouse-reeve/bookwyrm#190]
I think this project is a great idea, and I'm hoping to integrate it into the book reviews section of my blog when I rework that.

In the meantime, it'd be nice to:
  * poke around some running instances to see how it works
  * possibly find some interesting accounts to follow from my Mastodon account

Having a list of example instances somewhere (doesn't have to be in the readme, wherever is sensible...) would let people get more of a feel for it without having to spin up their own instance first.

**Comment by rkingett** [comment]
That is a great idea, but the problem is, there are no instances. Nobody has used this yet to make an instance. I loved the demo site when it was functional. I'm hoping someone will use it to make an instance soon because I am dying to leave Goodreads.

**Comment by mouse-reeve** [comment]
Unfortunately correct! I'll be able to start back into intensive work on it next week if all goes well, but there is still work to be done before it's ready to deploy at a production level.

**Comment by daveross** [comment]
I have a private instance running as of today. I'll need to learn a little Python before I can contribute a whole lot, but I'm happy to pitch in where I can. Got any good "first issues" for people to look at?

**Comment by MasterOfTheTiger** [comment]
I am certainly going to set up an instance when it is ready.

**Comment by mouse-reeve** [comment]
> I have a private instance running as of today. I'll need to learn a little Python before I can contribute a whole lot, but I'm happy to pitch in where I can. Got any good "first issues" for people to look at?

I went through and tagged some issues for this -- if any look interesting, I'm more than happy to talk more about the details :)
