### ISSUE TITLE
Error -2 connecting to redis:6379. Name or service not known.

### ISSUE THREAD

**Issue by jd7h** [mouse-reeve/bookwyrm#196]
Hello there! I've followed the instructions in the README.md to setup bookwyrm locally so I can view the project. However, when I try to add books or use the importer functionality, I get an error page:
```
Request Method: | POST
-- | --
http://127.0.0.1:8000/resolve_book
3.0.7
OperationalError
Error -2 connecting to redis:6379. Name or service not known.
(...)bookwyrm/venv/lib/python3.8/site-packages/redis/connection.py in connect, line 557
(...)bookwyrm/venv/bin/python
3.8.5
['(...)bookwyrm',  '(...)bookwyrm',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '(...)bookwyrm/venv/lib/python3.8/site-packages']
Sat, 12 Sep 2020 07:52:53 +0000
```
This gives me the feeling that the README might be missing Redis as a dependency and/or instructions for setting up Redis?

**Comment by mouse-reeve** [comment]
There is a redis dependency! Are you deploying with docker or no?

**Comment by jd7h** [comment]
Ah! I've followed the steps under 'Without Docker'.

**Comment by mouse-reeve** [comment]
okay, I definitely need to go through and update those instructions. Redis is a dependency for Celery, which is used for task management. I'll try and go through the set up process without docker and fix this

**Comment by mouse-reeve** [comment]
I think this is related to #793
