### ISSUE TITLE
UI review

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#202]
The poor, neglected user interface! My goal here is to get a holistic sense of what views the application should have, think about user flows, and create a serviceable if not beautiful interface pattern that is mobile-friendly. The best case scenario is structurally sound bones on which a design could one day live.
- [x] think out the types of users and their expected activities
- [ ] think through communicating and/or abstracting away technical details of federation and privacy
- [x] define application views
- [x] sketch basic wireframes
- [x] enumerate UI pattern library elements
- [ ] create the markup and css for the views
- [ ] #184 

The thinking parts are in the wiki.

Related tickets/sub-tickets: #204

**Comment by rkingett** [comment]
Only thing I can add here, as a totally blind person, is, well, ensure the font and contrast is nice and easy on the eyes! It may be a nice change if all instances had slightly larger font by default. This can be changed, of course, when people start making their own instances, but I often see contrast being a huge issue in 2020, even on mobile devices.

Other than that, just label everything! I'm glad this is still being developed.
