### ISSUE TITLE
null value in column "deleted_date" of relation "bookwyrm_status" violates non-null constraint error

### ISSUE THREAD

**Issue by ibrand** [mouse-reeve/bookwyrm#240]
**I see:**
A few variations of the following fullscreen Django error:
```
IntegrityError at /<the-route-hit>/
null value in column "deleted_date" of relation "bookwyrm_status" violates non-null constraint error
```

**When I:**
- toggle the state of the "start reading" toggle
- click post on a comment
- click post on a quote
- click post on a review

**My Current Theories / Questions**
My guess is that the DB is expecting `not null` on `is_deleted` but the state of the book doesn't default to `is_deleted` as `false`. I need to dig more into the data model to understand which part of the schema is having this issue. It could also be that a migration didn't fully run? Wanted to flag this before I dig into it in case it's a small thing that I'm missing since I'm new to the code

**Context**
This happens on a local env installed from the Docker instructions.

**Comment by mouse-reeve** [comment]
Oh I bet I know what happened. I initially wrote the deleted date to have a default value of "now" and then the next day realized that makes no sense, but I forgot to change the model field to be null-able and blank-able. This should be a straightforward change in the Status model
