### ISSUE TITLE
Let users revoke follow requests

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#282]
When a user sends a follow request, the send follow request button goes away and is replaced with `Follow request already sent.` text (`bookwyrm/templates/snippets/follow_button.html`).  Instead, the user should be able to cancel the request. 

Things I think that need to be done for this:
 - Replace the text with a "cancel request" button in the template
 - Create a local endpoint (in `bookwyrm/view_actions.py` that handles the behavior when that button is pressed
 - When the request is non-local, the view_actions endpoint should broadcast the activitypub Undo activity for the follow request (`bookwyrm/outgoing.py`)
 - Receive and handle incoming Undo activities for Undo Follow activities from external servers (`bookwyrm/incoming.py`)

**Comment by ahstro** [comment]
Oh, right, I should say: I'm looking into this, if that's cool? 😇

**Comment by mouse-reeve** [comment]
@ahstro that would be great! let me know if you run into any issues
