### ISSUE TITLE
let user edit review

### ISSUE THREAD

**Issue by hartsick** [mouse-reeve/bookwyrm#317]
**Is your feature request related to a problem? Please describe.**
I accidentally rated a book three stars and I absolutely need to rate it less.

**Describe the solution you'd like**
The ability to edit a review or star rating. I see we can edit the add and completion date for a book, but couldn't see how to modify a review once posted.

**Comment by mouse-reeve** [comment]
I hadn't thought about this since mastodon doesn't have editable posts, but now that I've thought about it, I think it should work fine, although I suspect that mastodon won't change reviews that it has received (which I think is an acceptable downside)

**Comment by cincodenada** [comment]
I really like Mastodon's delete-and-redraft feature as a replacement for editing, perhaps that's worth considering here as well!
