### ISSUE TITLE
Users can add books to custom shelves

### ISSUE THREAD

**Issue by hartsick** [mouse-reeve/bookwyrm#321]
**Describe the solution you'd like**
In addition to the 'to read', 'currently reading', and 'read' shelves, I'd love to be able to create custom shelves or tags for books, similar to Goodreads.

In past, I've mostly created shelves that map loosely to genre (e.g. `memoir`, `tech`, `management`) or mark something about the physicality of the book (`personal-library`, `zine`). To me these are slightly different than the standard "shelves", which are more about progress, so maybe it'd be more appropriate to think about them as tags? Then they could have a different page or way of sorting through than the current 'shelves' screen, which I think is really nice and straightforward.

**Importing from CSV**
When importing data from a CSV exported from Goodreads, there is a column named 'Bookshelves' that includes all shelving information for a book from the user's account. I believe right now BookWyrm adds books to the 'to read', 'currently reading', and 'read' shelves, but it would be great if it would also accept the user-specified shelves from Goodreads (for example, in the CSV [here](https://drive.google.com/file/d/1lhfrMBJp8iIZyS220rPeK3ozp5sv5OS9/view?usp=sharing) I have a shelf called `_personal-library` that I use to track books I own, which I'd love to have imported), creating new shelves in BookWyrm as needed.

**Comment by hartsick** [comment]
I now see this is on the product roadmap so sorry if it's duplicative!

**Comment by mouse-reeve** [comment]
I added user-created shelves (and shelf privacy settings), the remaining work is handling custom shelves in the import process

**Comment by mouse-reeve** [comment]
further work has a new ticket #449
