### ISSUE TITLE
Librarything import

### ISSUE THREAD

**Issue by eldang** [mouse-reeve/bookwyrm#345]
**Describe the solution you'd like**
I'd like to be able to import my Librarything catalogue

**Describe alternatives you've considered**
My current workaround is to export from Librarything to Goodreads, then export from there.  I may also play around with just renaming some fields in the Librarything export format and see if that works.

**Additional context**
In December or January I am likely to have some time to try to adapt the existing code for Librarything's format, and would be happy to have a go.

**Comment by mouse-reeve** [comment]
I want this feature too!

**Comment by eldang** [comment]
Well, if no-one beats me to it then I'll see if I can make it work in December.
