### ISSUE TITLE
Use timezone sensitive dates

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#357]
The default time zone is UTC, but that's not a great timezone for me! Django seems to have the potential to handle this better: https://docs.djangoproject.com/en/3.1/topics/i18n/timezones/

**Comment by SavinaRoja** [comment]
It appears that bookwyrm is currently configured to store datetimes as UTC aware, which is good.

Are there any places in the application where literal datetimes are displayed? If we allow users to configure their preferred timezone, then we could show those values in their timezone along with locationalization. I am aware of these points that could be adapted to user-local timezeone:

![imagen](https://user-images.githubusercontent.com/454944/112755587-41bebc80-8faf-11eb-9214-e3ca27c4ee67.png)

On the cards in the feed, I see that we have timedeltas displayed:

![imagen](https://user-images.githubusercontent.com/454944/112755670-b0037f00-8faf-11eb-997f-2cc4be8be952.png)

Which uses this segment of code:

![imagen](https://user-images.githubusercontent.com/454944/112755627-7468b500-8faf-11eb-85a0-3a0ae057efb9.png)

I would imagine that we could utilize something like [Arrow's humanize](https://arrow.readthedocs.io/en/latest/#humanize) to achieve this in a more localized fashion. If we could pass the locale into the django template (I think they only take one argument, so we might have to serialize-deserialize to move both the date and the locale in), we could achieve something like this:

![imagen](https://user-images.githubusercontent.com/454944/112756023-3ec4cb80-8fb1-11eb-82fd-6dd05de921cd.png)

![imagen](https://user-images.githubusercontent.com/454944/112756063-6451d500-8fb1-11eb-824a-c0b87216ad14.png)

**Comment by mouse-reeve** [comment]
The main place that the time zone thing bugs me is setting read dates in the modal when you start or finish a book. 
<img width="655" alt="Screen Shot 2021-03-28 at 10 35 39 AM" src="https://user-images.githubusercontent.com/1807695/112761708-64ea6b80-8fb1-11eb-9e50-579752c3cffe.png">

Django humanize has time ago filters already, I wrote the time since filter specifically because I wanted it to be ultra-concise, but I haven't updated it for internationalization.. At any rate, comparative dates aren't as much of an issue to me, since the amount of hours ago is independent of timezone, as long as all the dates are saved in the proper format.

**Comment by SavinaRoja** [comment]
@mouse-reeve Is this good to be closed?

**Comment by mouse-reeve** [comment]
yes! thank you
