### ISSUE TITLE
Statuses should automatically format links and mentions into html

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#377]
Right now, if you post a link, it remains plain text. If you @ mention a user, same thing. When a status is created, it should:
 - [ ] detect links and turn them into `a` tags
 - [ ] detect @ mentions
    - [ ] use the user database to resolve mentions 
    - [ ] use webfigner to resolve unknown mentions
    - [ ] format known mentions with an `a` tag, leave unknown ones as plain text
    - [ ] add mentioned users to the `mentions_user` database field
    - [ ] tag the user as mentioned in the activitypub object (this should happen automatically without any code change if the database field is set but I'm putting it in this list to be thorough)

**Comment by rkingett** [comment]
Could we include markdown support in these statuses as well as linking to books? Like, if I @ a book could we link that too? Or would that not work for the database? I also just like Markdown.

**Comment by mouse-reeve** [comment]
yes! supporting markdown is already in the roadmap (#37), and it didn't occur to me to let people tag books but it should definitely be possible. I think the simplest implementation of @ mentioning a book would be to turn a url that links to a book into a mention, since that's the most obvious unique identifier of a book. It would be better to allow a user to start typing a title and get suggestions, but that's another level of complexity (which should happen, but maybe not in the scope of this issue)
