### ISSUE TITLE
Books should be automatically moved based on activity.

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#378]
What I mean by this is, if a user presses I'm done, right now, when a  book is in the currently reading bookshelf, that book stays in the currently reading bookshelf.

If at all possible, I'd like this process to be similar to Goodreads, where the book is already moved to the, read, shelf, with a status containing my review upon finishing it.

This is probably in the works, but I wanted to put it here because I didn't see this feature request yet.

**Comment by rkingett** [comment]
By that same token, is there any way, if I change edditions, like from a paperback to an eBook, that previous paperback gets errased? Not sure how Goodreads does it, but that would make the site easier to use.

**Comment by mouse-reeve** [comment]
yeah, I know that goodreads lets you switch editions. I don't think that would be too hard to implement, and it'd be really useful

**Comment by mouse-reeve** [comment]
#126 is the relevant issue for switching editions, I'll try to address it today.

with regard to books not getting to the right shelf, can you tell me more about how to replicate the issue? Specifically, which page are you on when you press the button, and what is the button text? Also is there a book that should be showing as read but isn't at this moment on bookwyrm.social that I can refer to?

**Comment by rkingett** [comment]
Just noticed something else. When I review a book, not quote or comment on a book, the book stays in my currently reading shelf. Is this by design?

**Comment by mouse-reeve** [comment]
that is intentional. but I think with @cincodenada's work on #290 there can be a natural flow to review and mark as read

**Comment by rkingett** [comment]
Here's the steps to replicate. Let's use the book that's been haunting me for, like ages.

1. Go to [Ready Player 2.](https://bookwyrm.social/book/27091)
2. Add it to currently reading bookshelf.
3. Go to the homepage while logged in, or your shelves.
4. Go to currently reading. Expand the, ready player 2, tab.
1. Hit, I'm done! Button.
1. Fill in the dates.
1. Hit done.

The book stays in currently reading. Also, 

posting a review causes it to stay there as well.

**Comment by mouse-reeve** [comment]
I think that the reason the book isn't showing up as completed is that multiple editions are kicking around in the UI, and only the one you marked as read shows as completed. That means when you encounter a different edition (which could very well be visually and textually indistinguishable from the one you read) it appears that you didn't shelve the book.

Here's the workflow I'm thinking of implemented, which is mostly copied from goodreads: if I have an edition on my shelves, any other edition of the same book that I view will behave like it's on that shelf/in that reading state. So if I "start reading" an audiobook, the paperback edition (et cetera) will also show as "currently reading" in the updates feed or on the book page. In the editions list, only the edition that I'm reading shows as "currently reading" and the other editions give me the option to switch to that edition.

Switching editions will move my most recent reading dates to the new edition. I'm inclined to think that previous reviews should stay with the edition they were made on, but I'm not super sure.

I think this would solve both books appearing to be un-shelved after you shelve them and wanting to switch the edition you're reading.

**Comment by mouse-reeve** [comment]
Okay also I think it makes sense, on the book page, to show what shelf that specific edition is on. If you're on the edition page for the edition you're reading, it will show the change shelf pulldown (the same one that shows up in the table on the shelf page). If you're on the page for a different edition, it will indicate that you have a different edition on your shelves and show the button to switch to the current edition.

**Comment by rkingett** [comment]
I agree with everything! :)
