### ISSUE TITLE
Improve Mastodon integration by using the `application/activity+json` type

### ISSUE THREAD

**Issue by renatolond** [mouse-reeve/bookwyrm#429]
I'm not sure if this should be a bug, sorry if it's the wrong type!

**Is your feature request related to a problem? Please describe.**
When you follow someone from Mastodon, you don't see previous posts. One of the ways you can see them, however, is by pasting the URL of their status, which allows Mastodon to fetch that activity and associate with a profile. Currently, doing so with BookWyrm doesn't fetch the status.

**Describe the solution you'd like**
I'd like to be able to look for comments and profiles by pasting the URL in Mastodon search bar.

**Describe alternatives you've considered**
I think BookWyrm should use the `content-type` in the api request responses. This would make it so that Mastodon treat the responses as ActivityPub things and parses them correctly.
This however, raises another issues. It seems the serializer used in the views is serializing using `pure=False`, which gives a `Comment`, instead of a `Note`, which is ignored by Mastodon.
Since it probably would be interesting to still return BookWyrm-specific serializations, one way I see for this is to add a user-agent to bookwyrm requests and differentiate them in the views code.

I'd be happy to submit a PR about this if this is the way you think this should go :)

**Comment by mouse-reeve** [comment]
Yeah! I was assuming that the only time mastodon would receive statuses is when they are sent from bookwyrm, and it didn't occur to me that they should be fetch-able from mastodon as well. Bookwyrm instances definitely need the custom activity types (Comment, Review, Quote, etc) to each other, and "pure" versions of those statuses to mastodon, so I think your idea of using a user agent makes a lot of sense. So tl;dr you're right and I think your approach sounds correct. Thank you!

**Comment by mouse-reeve** [comment]
I'm getting a 500 error when I search for statuses in friend.camp that weren't posted to it. It looks like the bookwyrm server is responding with the "pure" activity as expected, but mastodon fails trying to load it.

**Comment by mouse-reeve** [comment]
okay, this turned out to be unrelated! false alarm.
