### ISSUE TITLE
aRSS feed support.

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#430]
I'd like the ability to share all, or part, of my Bookwyrm activity via RSS feed. If I can share an RSS feed of all, or part, of my activity on places like the bird site or my blog, this will help me produce content and give people more ways to follow me.

Goodreads has RSS feeds for your whole profile, and individual shelves, but, in truth, I'd just need one RSS feed that contains all my public updates, including public replies.

I'd just like one profile RSS feed that contains all my public updates I can share, or pipe, to various other people and platforms.

**Comment by mouse-reeve** [comment]
Upon some investigation, I think this would be fairly straightforward, since django has built in support for generating rss feeds:
https://docs.djangoproject.com/en/3.1/ref/contrib/syndication/
