### ISSUE TITLE
Hidden links to screen readers in navigation landmark

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#471]
To NVDA and JAWS on Windows, Not every link is visible in the navigation landmark without manually entering forms mode and tabbing through all the links one by one.

In the navigation landmark, the last link we can navigate to without going into forms mode is notifications.

Navigating to the main content landmark, then working backwards through shift tab, also does not reveal the settings link, imports link, and everything after notification.

Pulling up the links list also does not reveal these hidden links. One has to manually navigate to, notifications, enter forms/focus mode, then hit the tab key to get to the hidden links.

The settings, import, and everything after notification should be in the unordered list of links in the navigation landmark without having to do anything extra. Are they hidden behind a menu or something that automatically expands when interacting with the browser? Forms mode passes keys through directly to the browser, not the screen reader.

Would it be possible to make that DIV semantic HTML with those links  an UL? without the DIV?

This appears to be the problem. This isn't expanded until directly interacted with by the browser. Typically, screen readers don't automatically interact with browsers. On windows, everything is cued up in a virtual buffer. Kind of like a layor ontop of the browser.

` `DOMNode : div #mainNav .navbar-menu.toggle-content Click to select the node in the inspector` ￼

**Comment by mouse-reeve** [comment]
yikes, thank you for pointing this out; your proposed solution sounds right to me. Apparently my screen reader handles this totally different than yours, so I'll have to get you to test the fix for me when it's ready to be sure it's working properly.

**Comment by mouse-reeve** [comment]
okay! how does it work now?

**Comment by rkingett** [comment]
You use Mac right? VoiceOver is a bit better with DIVs but semantic HTML is always the best because it, quite literally, works with everything and across all browsers with nothing extra.

**Comment by rkingett** [comment]
Just tried the new menu and the only issue that NVDA is announcing it is expanded when it is collapsed and collapsed when it is expanded. Other than that, works great with the keyboard!

**Comment by mouse-reeve** [comment]
oh, janky! I think i know how to fix that.
