### ISSUE TITLE
Seeing my own profile feed on other people's profiles

### ISSUE THREAD

**Issue by dariusk** [mouse-reeve/bookwyrm#482]
**Describe the bug**
When I go to someone else's profile, the feed that is rendered under "User Activity" is my own.

**To Reproduce**
1. Go to anyone else's profile page and observe the result
![image](https://user-images.githubusercontent.com/266454/103687958-f95ea800-4f45-11eb-9f7c-03aae7498997.png)

**Expected behavior**
I see the other user's public posts rather than my own.

**Comment by mouse-reeve** [comment]
wow yep you _sure_ are. I bet this is a really easy fix at least
