### ISSUE TITLE
Bidirectional text support

### ISSUE THREAD

**Issue by imto1** [mouse-reeve/bookwyrm#490]
**Is your feature request related to a problem? Please describe.**
As you may know, the direction of Persian, Arabic, Hebrew, etc. texts is from right to left. Currently, all texts are displayed from left to right, and this is not suitable for displaying texts in the mentioned languages and it reduces its readability and consequently affects the user experience.

**Describe the solution you'd like**
Adding support for bidirectional text display.

**Comment by mouse-reeve** [comment]
@imto1 I believe this is fixed on bookwyrm.social, please let me know if problems persist

**Comment by imto1** [comment]
Yes it's fixed.
Thank you!
