### ISSUE TITLE
Duplicated Reading Activity Entries

### ISSUE THREAD

**Issue by nerdteacher** [mouse-reeve/bookwyrm#503]
Hello!

I'm noticing that I'm getting multiple instances of duplicated reading activity when pulling information from a Goodreads import. These occur primarily in two different areas: 1) changing to a different edition of a book that already as a reading activity entry (so I have a single reading activity that duplicates into two different entries) and 2) books that I unshelved and re-imported (some I'd unshelved by accident).

If it helps: I'm using Vivaldi.

For example:
![image](https://user-images.githubusercontent.com/77229429/104121057-cba9a280-533b-11eb-897a-639db9003cd8.png)
![image](https://user-images.githubusercontent.com/77229429/104121066-dd8b4580-533b-11eb-88fa-105c09425ad0.png)

**Comment by nerdteacher** [comment]
Just adding a bit more to this in case it helps? Because it seems that reading activity (also possibly ratings) are saved and automatically added to books when you change the edition, even you've deleted that information (in the case of reading activity) or unshelved the book entirely.

Same process (change edition):

![image](https://user-images.githubusercontent.com/77229429/104123843-a9b91b80-534d-11eb-9cf2-41b11eecd827.png)
![image](https://user-images.githubusercontent.com/77229429/104123886-dff69b00-534d-11eb-8e12-b47ac1990e57.png)

**Comment by mouse-reeve** [comment]
thank you! this fix should prevent it from happening on future imports, but won't remove existing duplicates
