### ISSUE TITLE
Content warning and text overflow toggles look the same

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#509]
The "show more" button is the same as the content warning button, it's confusing!

**Comment by rkingett** [comment]
For accessibility purposes, an HTML button would be best, but are you talking about the text of the button? Basically, I'd like buttons to stay semantic HTML if at all possible, especially since mobile devices don't handle ARIA or otherwise very well, including DIVS.

**Comment by mouse-reeve** [comment]
I'm going in and re-working this markup today, with semantic html in mind!
