### ISSUE TITLE
avatar in navbar is squished

### ISSUE THREAD

**Issue by binyamin** [mouse-reeve/bookwyrm#515]
**Describe the bug**
In the navbar, the user's avatar image is misshapen. In my browser (firefox, linux), it's 32px by 28px.

**To Reproduce**
1. Go to bookwyrm
2. Log in
3. Look at avatar image in navbar

**Expected behavior**
square, or cropped, image.

**Screenshots**
See issue below...
![2021-01-11_20-31](https://user-images.githubusercontent.com/39805353/104257938-8d4fd880-544c-11eb-8ce4-ec0be4a9d9cc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Ubuntu (budgie)
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 84.0.2

**Additional context**
About fixing it: It depends on what the desired effect is.
- If you want it at the 32x28 dimensions, use `.avatar { object-fit: cover|contain }`.
- Personally, I like it square. The culprit here is a `max-height` from bulma. You could add a `max-height: none !important` on `.avatar` or `.navbar-item img`.
- If you want to go even further, I think it looks nice with a teensy 2px or 4px `border-radius`. Kinda fits in more.

**Comment by mouse-reeve** [comment]
good catch! thank you

**Comment by binyamin** [comment]
Aw, I wanted to do that :stuck_out_tongue_winking_eye:.

**Comment by mouse-reeve** [comment]
oh my b! if you want to add a lil border radius I won't complain

**Comment by binyamin** [comment]
lol it's fine
