### ISSUE TITLE
Tabs do not work with arrow keys.

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#526]
OS: Windows 10, 2004.

Browser: FF 88 or 87. The latest one.

I was trying an experiment on Bookwyrm to see if any of the tabs could be navigated by the keyboard. In short, sadly, I wasn't able to find any.

I passed through commands to the browser, not my screen reader, and tried to use arrow keys to switch from, for example, the review tab on a book products page to the comments tab.

When I passed through the keys to the browser directly, pressing my tab key seemed to jump right over the 3 tabs.

I tried to navigate them with the arrow keys but I couldn't.

I'm pretty sure HTML can't make tabs, so you would have to make the tab index 0 I think.

You can also make a <div> or <span> keyboard accessible by adding a tabindex of 0. This is particularly useful for components that use interactive elements that do not exist in HTML.
Grouping controls
For grouping widgets such as menus, tablists, grids, or tree views, the parent element should be in the tab order (tabindex="0"), and each descendent choice/tab/cell/row should be removed from the tab order (tabindex="-1"). Users should be able to navigate the descendent elements using arrow keys.

[This page seems to have some killer examples.](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets)

**Comment by greatislander** [comment]
This is a specific example of how one might implement tabs with expected keyboard controls: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

See also: https://github.com/zachleat/seven-minute-tabs

@mouse-reeve I'd be happy to take a crack at opening a PR for this if you would like!

**Comment by rkingett** [comment]
In this case, I'd rather they stick with DIVS and javascript rather than using ARIA. As close to native as possible would be best.

**Comment by greatislander** [comment]
@rkingett Understood—does the behaviour of the tabs in the linked example make sense from the keyboard perspective? I think the use of ARIA roles is fairly minimal and probably could be mostly omitted (the one ARIA attribute that might make sense to include would be the one which indicates that a tab is currently active—thoughts?).

**Comment by mouse-reeve** [comment]
> @mouse-reeve I'd be happy to take a crack at opening a PR for this if you would like!

@greatislander Normally I would be 100% in for this, but right now I'm refactoring how all the html interactive elements work, so we would be destined for terrible merge conflicts. I'll link the PR here when I make it, after it's merged I'd be very pleased to let you go for it.

**Comment by rkingett** [comment]
Yes, let's see what @mouse does. But I think HTML can't make tabs, so this would be a case where we'd have to use javascript and set the tabindex =0, but I am quite sure @mouse is getting the hang of inclusive design.

**Comment by mouse-reeve** [comment]
@greatislander go wild.
