### ISSUE TITLE
Hmm. Comments disabled in book reading goals?

### ISSUE THREAD

**Issue by quaayd** [mouse-reeve/bookwyrm#535]
**Describe the bug**
I was unable to comment on my 'goal to read post'. Also another user's.

**To Reproduce**
1. Go to 'quaad set a goal to read 1 books in 2021'
2. Click on 'comment button'
3. box is highlighted but no comment window pops up.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chome
 - Version 87.0.4280.88
 - 

**Additional context**

**Comment by mouse-reeve** [comment]
do you have javascript disabled? and if not, can you try hard refreshing (command-shift-r on mac)?

**Comment by quaayd** [comment]
hard refreshing worked! thanks. kind of a dud for my first issue posting. :(

**Comment by mouse-reeve** [comment]
no worries! thank you for reporting :)
