### ISSUE TITLE
About page requires login

### ISSUE THREAD

**Issue by Aethelflaed** [mouse-reeve/bookwyrm#549]
**Describe the bug**
Accessing the "About this server" link (https://bookwyrm.social/about) redirects to login

**To Reproduce**
1. Go to https://bookwyrm.social/about
2. redirected to login instead of seeing an about page (the URL is login/?next=/about)

**Expected behavior**
Access to information about this site / server

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 85 (developer edition)

**Comment by mouse-reeve** [comment]
Oops! thank you for pointing this out.
