### ISSUE TITLE
Edit book author

### ISSUE THREAD

**Issue by Fuxino** [mouse-reeve/bookwyrm#551]
Hi, some of the books I imported are missing the author, see this one for example:
![Screenshot from 2021-01-20 17-44-56](https://user-images.githubusercontent.com/9594904/105209992-c3771180-5b4a-11eb-95e1-7b283719e4cb.png)
When editing the book there is no "Author" field, so I'm unable to add it manually. Is it possible to add a field for editing the author?
Thank you :)

**Comment by mouse-reeve** [comment]
yeah! this is an important missing feature
