### ISSUE TITLE
Add Ability to Track Progress in a Book

### ISSUE THREAD

**Issue by bcj** [mouse-reeve/bookwyrm#56]
I would like to be able to keep track of where I am in a book as I am reading it (e.g., page number or equivalent for an ebook).

It would be nice if this kind of update optionally created a status for it (I may want to post a status if I got to a pivotal part in a book or finished a book in a collection, but not want to spam my followers if I am just updating my place in a book I'm reading)

**Comment by mouse-reeve** [comment]
definitely should be a feature. I'm not sure if it should go on the ShelfBook table or be stored separately from that.

**Comment by cincodenada** [comment]
#354 was just merged, which accomplishes the first part of this - you can now track your progress through a book as you go.

It won't post anything to your feed yet, but optionally posting an update is next on my list :)

**Comment by mouse-reeve** [comment]
I think this is resolved with #774! Feel free to reopen if there are any further changes needed
