### ISSUE TITLE
Did Spoilers disappear?

### ISSUE THREAD

**Issue by quaayd** [mouse-reeve/bookwyrm#565]
I wanted to write a review of the Mill on the Floss and use the spoiler button but could not find it.

Went to my shelves, clicked on the book, selected Review tab. No spoiler button.

Went back through my old posts to find one where i had used the spoiler alert function. there is a 'show more' button, but no mention of spoilers.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Firefox
 - Version 85.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mouse-reeve** [comment]
They didn't disappear, but I changed the UI -- next to the privacy pulldown, there's a little warning triangle icon that toggles content warnings

**Comment by quaayd** [comment]
at least my perfect record is intact.
