### ISSUE TITLE
Still get notifications for follows from blocked user

### ISSUE THREAD

**Issue by hartsick** [mouse-reeve/bookwyrm#579]
**Describe the bug**
I blocked https://bookwyrm.social/user/followbot@search.fedi.app, but I'm still getting follow notifications from them. I also can still see them in my followers list

**To Reproduce**
1. Block user that currently follows you
2. View own follow list, see that they still follow you
3. Have that user (while blocked) refollow you
4. See notification for that follow

**Expected behavior**
I expect that a block would force a user to unfollow me. Even if this didn't happen, though, I'd like to no longer receive notifications from activity of users that I've blocked, including follow notifications

**Comment by mouse-reeve** [comment]
#594 and #609 should go a long way towards fixing this, but it needs a bit more looking-at before it's closeable
