### ISSUE TITLE
Is there a list of instances?

### ISSUE THREAD

**Issue by ScootRay** [mouse-reeve/bookwyrm#597]
Greets,

I stumbled upon this via OpenLibrary's blog and am fascinated with the possibilities of it. Love how it looks so far.

Is there a list of instances using Bookwyrm somewhere? 

If not, would folks be so kind as to share them here?

Thanks,
Ray

**Comment by mouse-reeve** [comment]
There is now :) https://github.com/mouse-reeve/bookwyrm/blob/main/instances.md

**Comment by ScootRay** [comment]
Sweet! Look forward to watching it fill up. : )

Thanks for all you do,
Ray

--==> Follow me Along the Ray @ alongtheray.com... <==--

writer / shutterbug / wanderer / lifelong entrepreneur / reiki master / oral deaf / zigs when others zag / nature lover who kayaks to work ; )
