### ISSUE TITLE
Make book covers clickable

### ISSUE THREAD

**Issue by ScootRay** [mouse-reeve/bookwyrm#598]
Several times I've clicked/tapped on a book cover thinking it would take me to the book only to find I need to click the book title instead.

From a usability standpoint it makes sense to wrap the covers in the book's URL so it is clickable as well.

Thanks!
Ray

**Comment by rkingett** [comment]
Agreed. Make sure to preserve alt text, too. Actually, speaking of, is there a way we could include the edition in the alt text?

**Comment by mouse-reeve** [comment]
I agree on this as well. In most places, covers already are clickable - the only places I noticed that aren't is on the shelf page, and in the list preview, both of which I can change. 

In terms of the alt text, I've tried to make it clear about which edition is being shown using metadata about the book using the title, physical format, and date published, but when that metadata is absent I'm not sure how to better indicate which edition is which. Unfortunately there just isn't differentiating metadata available on a lot of the editions.
