### ISSUE TITLE
Production Server Setup Instructions Incorrect on how to Give a User Administrative Access

### ISSUE THREAD

**Issue by bcj** [mouse-reeve/bookwyrm#620]
**Describe the bug**

`models.User` objects do not contain an `is_admin` attribute.

**To Reproduce**
1. run `./bw-dev shell`
2. fetch the appropriate `models.User` object
3. Attempt to set `is_admin = True`
3. See error: `AttributeError: 'User' object has no attribute 'is_admin'`

**Expected behavior**
Either `is_admin` is re-added or the instructions are updated to include the correct command (is it something involving `User.user_permissions`? That's the only visible attribute that looks like it could be related)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - InteractiveConsole
 - Version: `production` (`a2c7bff`)

**Comment by mouse-reeve** [comment]
Ah yeah I think this just isn't a thing and shouldn't be there! settings `is_staff` and `is_superuser` is I think the correct process
