### ISSUE TITLE
Show posts that were posted in private mode

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#626]
**Is your feature request related to a problem? Please describe.**
I posted some quotes and comments and choose "Private". I can't find them anymore.

**Describe the solution you'd like**
I'd expect them to show up (while being logged in as me):

- on my profile between my other (public) posts.
- on the book they belong to 

**Describe alternatives you've considered**
A special place where private posts are shown

**Additional context**
Maybe I just looked in the wrong places, but I think I checked about every place.

**Comment by tofuwabohu** [comment]
They show up in the "Direct messages" section, so there is a way to see them, I just hadn't found it.

**Comment by mouse-reeve** [comment]
yes, they do. but the behavior that I think would be better is if book-related content shows up where you'd expect it (in the feed, on the book page), and the dms page is only for actual private conversations not about a book. thanks for flagging :)

**Comment by tastytea** [comment]
Is this change on bookwyrm.social already and did I understand it correctly that my quotes and DMs about a book are supposed to show up in `…/book/…` pages? Because they don't. Or does it only apply to new content?

**Comment by mouse-reeve** [comment]
The only content that shows up on book pages is reviews, so quotes only show up in your updates timeline and on your profile page. After this change, private reviews that you make should show up on the book page, and not in your dms page
