### ISSUE TITLE
Indicate that a file is selected when adding a cover

### ISSUE THREAD

**Issue by tastytea** [mouse-reeve/bookwyrm#628]
**Is your feature request related to a problem? Please describe.**
I wanted to add a cover for a book, but it looked like the selection silently failed.

**Describe the solution you'd like**
This is how it looks like now, after a file is selected:

![screenshot_2021-02-21T23:03:30](https://user-images.githubusercontent.com/3681516/108640580-d870f880-749a-11eb-9a48-4c55b264eaac.png)

It would be nice if the UI would indicate that a file is selected, for example by showing the filename.

**Comment by mouse-reeve** [comment]
agreed! this is the one part of the css framework that I think is a real step backwards. I'll revert it to the normal upload form
