### ISSUE TITLE
Pleroma not recognizing follow request Accept activity

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#634]
When I follow a bookwyrm user from pleroma, the follow request is received in bookwyrm and the `Accept` is sent out, ostensibly successfully, but poleroma doesn't recognize that the follow request has been approved. It appears to work fine in the other direction (following a pleroma user from bookwyrm).

**Comment by tastytea** [comment]
I've reported the issue on the Pleroma bug-tracker here: <https://git.pleroma.social/pleroma/pleroma/-/issues/2537>.
