### ISSUE TITLE
Provide a Bookwyrm-only image

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#658]
While the provided Docker image is great for running Bookwyrm from scratch, I'd like to run it on a machine where some requirements are already installed, e.g. Postgres, Redis and Caddy in favor of Nginx.

Would it be possible to have an image which contains Bookwyrm, Celery and Flower only, so that the UI can be proxied to from the outside?

**Comment by mouse-reeve** [comment]
This definitely sounds possible! I'm not deft enough with docker to know how to do this off the top of my head, so I'm going to flag this as help wanted. Thank you for raising

**Comment by Flameborn** [comment]
I am trying to contribute a Dockerfile for this, but I am running into some issues when trying to do this on a Raspberry Pi first, from source.

## What I've done:

* I have Redis, and Postgresql installed and configured.
* I copied *.env.example* to *.env* and modified it.
* I ran *manage.py initdb* and *manage.py migrate*.
* I registered a user and set it as the superuser, as per the README.

I have a shell script that does the following:

```
#!/usr/bin/bash
cd /home/bookwyrm/bookwyrm
source .env
celery -A celerywyrm worker -l info &
./.local/bin/flower --port=8888 &
./.local/bin/gunicorn bookwyrm.wsgi:application --bind 0.0.0.0:8000 &
```

## What Issues I get

* Static files does not seem to be served, i.e. I am getting every single item on a page, when using a screen reader, and I see *500* server errors when trying to GET a *CSS* or a *JS* file.
* Emails, for example the *Forgot Password* one, return with a "Connection closed unexpectedly" error.

The static files seem to be served properly when *DEBUG* is set to *true*.

 I am using Mailgun, my *EMAIL_USE_TLS* variable is set to *true*.

I've also tried Django's *EMAIL_USE_SSL* in combination with this, unfortunately without any luck.

Any pointers would be greatly appreciated ☺️

**Comment by mouse-reeve** [comment]
hmm, it could be that you need to run `./bw-dev collectstatic` or `python manage.py collectstatic` in order to get the static files in the right place? They're served through nginx in the current setup, and docker has volumes which those images connect to, so maybe the webserver setup you have replacing nginx isn't finding the static directories correctly?

**Comment by Flameborn** [comment]
Ah, I was under the impression that Gunicorn would serve the static files as well, along with the HTML views.

I've added this as an extra directory, and now it seems to work as expected. I am using Caddy as a web server, by the way.

I am guessing that the email issue is likely outside your control, as it's Django's mail lib.

I am going to see what I can do regarding the image and send a PR when it's ready.

**Comment by mouse-reeve** [comment]
I wonder if the email issue is related to connecting to Celery and Redis? Sending happens in a celery task

**Comment by Flameborn** [comment]
I think I am getting the error inside the Celery task, so this is likely not a Bookwyrm issue. I remember having a similar issue via a PHP library as well, it could be an incompatible TLS/cypher version being used, for example. I am getting:

```
[2021-03-03 08:51:24,857: INFO/MainProcess] Received task: bookwyrm.emailing.send_email[df4f9f4c-b6be-4a0a-be49-0f89cbf3238b]
[2021-03-03 08:51:33,284: ERROR/ForkPoolWorker-1] Task bookwyrm.emailing.send_email[df4f9f4c-b6be-4a0a-be49-0f89cbf3238b] raised unexpected: SMTPServerDisconnec
ted('Connection unexpectedly closed')
Traceback (most recent call last):
  File "/home/alarm/.local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/alarm/.local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/hd/bookwyrm/bookwyrm/emailing.py", line 19, in send_email
    send_mail(
  File "/home/alarm/.local/lib/python3.9/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/home/alarm/.local/lib/python3.9/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/alarm/.local/lib/python3.9/site-packages/django/core/mail/backends
/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/home/alarm/.local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.9/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.9/smtplib.py", line 425, in docmd
    return self.getreply()
  File "/usr/lib/python3.9/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

I have looked into creating a Bookworm-only image. Unfortunately, connecting to an external service from Docker is tricky. For example, under Linux, the recommended way is to use the Docker bridge interface, via the IP *172.17.0.1*. This only works if I bind to 0.0.0.0 in my Postgres and Redis configs.

I think currently this Docker setup is less than ideal, so I will likely run Bookwyrm via a non-Docker install for now.

Thank you very much for the pointers regarding the static files and the email feature, it is very much appreciated.
