### ISSUE TITLE
403 attempting to login

### ISSUE THREAD

**Issue by suite22** [mouse-reeve/bookwyrm#663]
![6A0CC90F-F750-4128-83AA-BB02D4E649BD](https://user-images.githubusercontent.com/918105/109430197-f2d43600-79b4-11eb-8855-a58decfda03e.png)

It looks like if I open another tab I am logged into my account though.

**Comment by mouse-reeve** [comment]
yikes!

**Comment by suite22** [comment]
Thanks! 🥳
