### ISSUE TITLE
Allow manually adding a book

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#671]
Currently, as far as I can tell, there is no way to add a book other than importing it from an existing source.

Bookwyrm should allow adding books manually, either by users with the appropriate permission, or on a per user basis, so that users who search for the same book can decide to import it locally or on a different server (should the book  info be public).

**Comment by mouse-reeve** [comment]
yes! I'm literally working on that right now :)

**Comment by Flameborn** [comment]
This is going to make a lot of people happy. Thank you very much!
