### ISSUE TITLE
Remove the "Cover" text from the alt text of book covers if one is present

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#694]
Currently, when a book cover is present and is displayed, it's alt text consists of the book title, the text *Cover*, edition name, and the first published date.

For example, via VoiceOver under Safari:

```
image The Night Circus cover (Hardcover, 2011)
```

The fact that this is a cover image is redundant, because users are already notified about the presence of an image. In this case, the textual data is actually more important, e.g. book title and edition name, since the presence of a cover does not add more information when using a screen reader.

The expected result, via VoiceOver (and possibly other screen readers as well) is:

```
image The Night Circus (Hardcover, 2011)
```

**Comment by rkingett** [comment]
I agree. Can't believe I didn't notice this. I guess I've become used to it, but I agree.

**Comment by mouse-reeve** [comment]
I love an easy issue :)

**Comment by Flameborn** [comment]
Thank you very much. I think users love an easy fix too ☺️
