### ISSUE TITLE
Wrong user shown on boost message

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#706]
**Describe the bug**
In the home and federated tl, when someone is boosting a post, the display name of the original poster is shown instead of the booster's display name.
On the profile of the booster, it's shown correctly.

**To Reproduce**

1. Go to the home or federated tl
2. Check for a boost of a post

**Expected behavior**
The display name of the booster should be shown

**Screenshots**
Wrong, from the home tl:
![image](https://user-images.githubusercontent.com/66644064/110258226-d7af8a80-7fa1-11eb-91db-54a3ec4d3caf.png)

Correct, from the user's profile on bookwyrm:
![image](https://user-images.githubusercontent.com/66644064/110258288-2c530580-7fa2-11eb-8433-029e332bc86b.png)

**Comment by mouse-reeve** [comment]
my b! thanks for catching and reporting this

**Comment by tofuwabohu** [comment]
Wow that has been fast!

**Comment by mouse-reeve** [comment]
I broke it this morning, so it was fresh in my mind
