### ISSUE TITLE
Allow fetching cover via a URL

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#711]
Currently, Bookwyrm accepts a physical file as an upload when specifying a cover, it would be awesome if it could fetch the cover from a given URL.

This is especially handy when the cover is already present on a site, e.g. Google Books, Goodreads, or on the publisher's/author's site.

**Comment by mouse-reeve** [comment]
omg this is 1000x better than uploading files, thank you for getting me to do this

**Comment by Flameborn** [comment]
The pleasure is mine. Thank you so much for implementing it as quickly as you did.
