### ISSUE TITLE
Allow books on multiple shelves

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#716]
A user should be able to have a book on multiple shelves. Books are automatically moved between shelves when the reading status is updated, but I don't _think_ that will cause any issues. Prior conversation on this is in #115.

**Comment by LongJohn-Silver** [comment]
In my opinion books should be allowed to be on multiple shelves except the three "To read", "Reading" and "Read". If someone would want to to re-read a book in my opinion there should be something like a button where you click "Re-reading" and it "resets" these three shelves, adding a number to a counter each time you read this book.

**Comment by mouse-reeve** [comment]
I think #800 resolves this. In regard to re-reads, your read-throughs are tracked and visible on the book page, so those are counted, although they aren't shown along with the shelf.
