### ISSUE TITLE
Cannot Cancel a Follow Request and Cannot Block a User if you have a Pending Follow Request With Them

### ISSUE THREAD

**Issue by bcj** [mouse-reeve/bookwyrm#721]
**Describe the bug**

Once you've sent a follow request to an account, there does not appear to be a way to cancel that follow request. This removes the button that allows you to block that user

**To Reproduce**
1. On account A, set `Manually approve follower` to true
2. From account B, go to A's profile click the `Send Follow Request` button
3. Don't approve the follow request. B can no longer block A

**Expected behavior**

The `Send Follow Request` button should turn into a `Cancel Follow Request` button and should maintain the menu button for blocking users

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Firefox
 - Version 87.0b9

**Comment by mouse-reeve** [comment]
#426 is related to this
