### ISSUE TITLE
Add publisher as a book field

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#729]
Currently, the only way to distinguish editions is by their cover and their publication date. It would be nice if editions were also referred to by their publisher.

This is especially useful as part of the alt text of a cover for screen reader users, but also great for people who would like to catalog which edition is by which publisher. I believe OpenLibrary provides a publisher field as well, so this could be automagically filled during an import.

**Comment by mouse-reeve** [comment]
Luckily this data is in the database, it's just not being displayed anywhere :)

**Comment by mouse-reeve** [comment]
I merged that PR preemptively, oops

**Comment by Flameborn** [comment]
I don't see an issue with that ☺️

Checking this in production, the only thing that is missing at the moment is a field on the edit page to be able to edit the publisher.

I'd also change the alt text on the covers to be in the format: Format, Publisher, Publication year. This will make it so that editions can be also distinguished by their cover via a screen reader.

**Comment by mouse-reeve** [comment]
yep, those two changes are the ones I meant to do before I merged that and closed this issue
