### ISSUE TITLE
Reading Activity for an edition I haven't read is showing confusing [badly imported] entries

### ISSUE THREAD

**Issue by loppear** [mouse-reeve/bookwyrm#749]
**Describe the bug**
Looking at another edition of a book I have read, I see Your Reading Activity that is perhaps every other person's reading activity? The view of the edition I rated is correct. Another edition (that maybe doesn't have any reading activity from anyone) shows "A different edition is on your read shelf" twice. See attached screenshot.

Probably something 

**To Reproduce**
1. A quick browse does not show other books I've read showing this issue - can't easily see if those books don't have other users who have reading activity on a different edition?
2. But since https://bookwyrm.social/book/56 has mixed reading activity, hopefully it's happening for others there too.

**Expected behavior**
My reading activity for me, yours for you.

**Screenshots**
<img width="812" alt="Screenshot 2021-03-15 203643" src="https://user-images.githubusercontent.com/539208/111238885-72295280-85ce-11eb-9270-0e5e0d7347fd.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 87.0b6

**Comment by mouse-reeve** [comment]
I suspect it's showing you your reading activity for other books. Did you import goodreads data? and if so, approximately how recently?

**Comment by loppear** [comment]
Oh, that's a better theory. This book  was from an initial goodreads import (2 months ago?) and has a couple other data oddities hinted at in that screenshot. I haven't re-run a goodreads import since.

**Comment by mouse-reeve** [comment]
okay, what I think happened is, you uploaded during a period where there was a bug what caused a bunch of books to be misidentified in the import process (usually as _Hamlet_, but it's fitting that it happened with _The Raven Tower_ too) (basically it matched books with low id numbers). As a result, it imported a bunch of your data incorrectly. I actually removed a bunch of clearly misattributed reviews as well. It sucks! There's not an easy fix for the existing bad data, but I believe, at least, that the import bug is fixed.

**Comment by loppear** [comment]
Thanks. Having confirmation these are not a display/permissions issue but bad import data makes me more confident in deleting them through the interface when I encounter them now.

Is there any sense in re-running the GR import for cleaning up or adding in the misattributed data? Other than that pointer, this issue is fine to close.

**Comment by mouse-reeve** [comment]
You could definitely re-run the import! If you include reviews, you might end up with some duplicate reviews, which imo isn't that big a deal, but if you don't, it should avoid duplicating your read dates or wildly reshelving your books
