### ISSUE TITLE
Can't contact (remote) profiles when they don't have an avatar

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#755]
**Describe the bug**
From Bookwyrm instance a, I can find @user@b (also Bookwyrm) with the search, but only when the user has an avatar set. Looking up users without an avatar results in Internal Server Error. You also do not get PMs from those users.

**To Reproduce**
Go to https://wyrms.de and look for a user w/o avi, e.g. @luxon@bookwyrm.social (direct link: https://wyrms.de/search/?q=%40luxon%40bookwyrm.social)

Proof the profile exists: https://www.bookwyrm.social/user/luxon

There was another account I tested this against, they got an avatar then and after that, the communication worked.

**Expected behavior**
Contacting other accounts should be possible whether they have an avatar or not.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/66644064/111466095-220fd480-8723-11eb-801d-63b802f530fb.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/66644064/111466118-2d630000-8723-11eb-8564-e65c17c32c9a.png)

**Additional context**
There was a similar bug, maybe the avi ist still not sent properly. https://github.com/mouse-reeve/bookwyrm/issues/50

**Comment by mouse-reeve** [comment]
thanks for catching this!
