### ISSUE TITLE
Allow me to disable reading goals

### ISSUE THREAD

**Issue by tastytea** [mouse-reeve/bookwyrm#757]
**Is your feature request related to a problem? Please describe.**
I don't want to set a reading goal but I am asked every time I log in.

**Describe the solution you'd like**
I would like a checkbox in the settings to disable reading goals. Maybe an extra button / checkbox “Don't ask again” in the message too?

**Comment by mouse-reeve** [comment]
oh dear, it's definitely supposed to go away and not come back if you dismiss it! The dismissal is stored in localstorage, so maybe that's getting reset more often than I expected.

**Comment by tastytea** [comment]
I just tested again, it is not asking every time I log in, but every time I restart the browser and then log in.
I delete all cookies when the browser exits, maybe that deletes localstorage too?

**Comment by mouse-reeve** [comment]
I think it makes sense to store this in the database, since it shows up all year when unset. I plan on putting other things in local storage, but only things that are much less intrusive. Thanks for flagging this!
