### ISSUE TITLE
Shorten steps to read reviews with spoilers

### ISSUE THREAD

**Issue by rkingett** [mouse-reeve/bookwyrm#758]
**Describe the bug**

Using NVDA on Windows, it seems as though I have to expand three toggles to read a review that contains a spoiler. For keyboard users, this could get very tiring very quickly, especially when browsing the site for some time.

When I come across a review with a spoiler, I have to,

1. First expand the spoiler.
2. Then expand the review.
3. then expand the review excerpt into the full review.

**To Reproduce**

1. Run NVDA/VoiceOver in a native Desktop browser, or VoiceOver on IOS,
1. Go to a review containing a spoiler warning.
2. navigate to the toggle hiding the spoiler.
3. expand the spoiler toggle, then try to read the review.
4. You'll notice that now, the review has to be expanded.
5. Toggle the review view.
6. Now, you'll notice the review is excerpted.
7. expand the excerpt to the full review.

**Expected behavior**

I'd ideally like one toggle state to deal with reviews with spoiler warnings.

OS: Windows 10, 2004.
Browser: Firefox 88.
 

**Smartphone (please complete the following information):**
Device: iPhone SE, 2020.

OS: IOS 14.5.
 - Browser stock browser, safari]
 -

## Possible solutions.

1. [Use one expand/collapse menu based on details, like this one](https://dequeuniversity.com/library/aria/expand-collapse-summary)
2. Try this expand/collapse, without details, for reviews containing spoilers](https://dequeuniversity.com/library/aria/expand-collapse)
3. Keep the element, button toggle, as is. I prefer this because it communicates states, and put the variables under one toggle button rather than 3? Like, for example, have one toggle button for spoiler reviews that reveals the whole review when the spoiler is expanded.
I like option 3 the best. If possible, I'd want to keep the toggle buttons because they communicate a state, which I like more than using an expand menu.

**Comment by mouse-reeve** [comment]
Yes! The current setup for this is too many clicks and also confusing, thank you

**Comment by rkingett** [comment]
Closing this issue. Not sure why it didn't close.
