### ISSUE TITLE
Show more doesn't work on review pages

### ISSUE THREAD

**Issue by tastytea** [mouse-reeve/bookwyrm#768]
**Describe the bug**
“Show more” isn't working on review pages, but it works on book pages.

**To Reproduce**
1. Go to <https://bookwyrm.social/user/hunterowens/review/19022>
2. Click on 'Show more' → Nothing happens
3. Click on the book title
4. Scroll down to review
5. Click on 'Show more' → It shows more

**Desktop:**
 - OS: **Linux**
 - Browser: **Firefox**
 - Version: **78.8.0esr**

(Same with Falkon 3.1.0)

**Comment by rkingett** [comment]
Can confirm this does not work on the keyboard side either.

**Comment by mouse-reeve** [comment]
woops yes I broke that!
