### ISSUE TITLE
Boosts do not propagate to Mastodon

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#779]
**Describe the bug**
When I boost a status with a BW-account, it is shown on my profile and on other BW instances. It is not shown for following Mastodon users though. Also, the OP will not get notified that you boosted the statust in some cases, e.g. if they are on Mastodon. Sometimes happens across bw instances too, could not reproduce this yet.

**To Reproduce**
1. Boost a status with a BW account
2. Check the BW account remote from Mastodon and the notifications of the OP

**Expected behavior**
The status should get boosted into Mastodon (and other AP platforms) user's timelines and the OPs should get notified.

**Screenshots**
Me boosting a 21h old status on bw:
![image](https://user-images.githubusercontent.com/66644064/111921668-0d6e6c00-8a96-11eb-90b2-d2df217e5c23.png)

My account from Mastodon (has been followed all the time), last activity my own status 5d ago:
![image](https://user-images.githubusercontent.com/66644064/111921700-43135500-8a96-11eb-8e11-4c9bc9da6ca9.png)

**Comment by mouse-reeve** [comment]
Huh! I just replicated and I have a sucessful celery task, so it's not a broadcast issue. There may be something wrong with the activitypub that's causing mastodon to reject this; I'll take a closer look at the response I'm getting from mastodon.
