### ISSUE TITLE
Review  - Comment - Quote tabs don't change in book template

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#782]
**Describe the bug**
The default tab in the book page is "Review". Clicking "Comment" or "Quote" doesn't change the active tab, "Review" stays open.

**To Reproduce**
1. Go to a book page, e.g. https://bookwyrm.social/book/1
2. Click Comment or Quote
3. ![image](https://user-images.githubusercontent.com/66644064/112040152-22ee9f00-8b45-11eb-90d9-0e6becfeba9c.png)

**Expected behavior**
The current tab should be changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/66644064/112039692-98a63b00-8b44-11eb-9e27-22c449a3223a.png)

**Desktop (please complete the following information):**
    - OS: Arch Linux with KDE Plasma
    - Browser: Firefox
    - Version 86.0.1 (64-bit)

**Smartphone (please complete the following information):**
    - Device: Fairphone 3
    - OS: Android 10
    - Browser Firefox
    - Version 82.1.3

**Comment by mouse-reeve** [comment]
woops! I forgot to include the javascript that controls that on that page when I refactored. thanks so much!
