### ISSUE TITLE
Following across instances doesn't work in a few cases

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#788]
**Describe the bug**
[tastytea@bookwyrm.social](https://bookwyrm.social/user/tastytea) can not follow me on [tofuwabohu@wyrms.de](https://wyrms.de/user/tofuwabohu).

They sent a follow request which I accepted. On wyrms.de, they show up on the list of accounts that follow me, but on bookwyrm.social, they don't, and my account is not in the list of accounts they are following. w.d seems to think the following was successful, b.s still waits for the following confirmation.

**To Reproduce**
We "cancelled" the request with a workaround (I blocked and unblocked them) and tried again, but the result is the same. I also unlocked my account for a short while to try it without the confirmation process, but on b.s my account was still shown as locked. From w.s, that "request" was immediately accepted, but b.s seems to be waiting for confirmation.

**Additional context**
Other users from b.s could follow me and someone else on w.d without problems.

I restarted the docker containers in the meantime, so I don't have flower logs of the process anymore. We could redo the process again if that's of help for debugging. I took this screenshot the last time:

![screenshot of the flower service, stating the following process was a success](https://user-images.githubusercontent.com/66644064/112313466-29e1f280-8ca8-11eb-8a2d-5aefd15559cb.png)

cc @tastytea

**Comment by mouse-reeve** [comment]
hm, I tried this just now between my dev instance and mastodon, and my dev instance and b.s and it worked. One possible cause is that b.s's celery instance was running super slow and/or dropped the task. Would you be willing to try the follow again and see if we can replicate the bug?

**Comment by tofuwabohu** [comment]
We tried and now we could follow each other. :) I didn't get a notif that tastytea followed me (there's an older one of them following me in my notif's history though, maybe it doesn't allow duplicates?) but everything else seems to work. Thanks!

**Comment by mouse-reeve** [comment]
Yay! And yep, the notification model deduplicates automatically, but I guess it should be keeping the more recent instance, or updating the created_date accordingly

**Comment by tofuwabohu** [comment]
Probably related: Tried to follow me from an old Mastodon account on social.tchncs.de to see if everything works but didn't get a notification and flower error'd.

![image](https://user-images.githubusercontent.com/66644064/112516768-e797de80-8d97-11eb-8aa4-7b37f0a017b1.png)

Details:

Exception: NameError("name 'get_activity' is not defined")
Traceback:
``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/bookwyrm/views/inbox.py", line 69, in activity_task
    activity.action()
  File "/app/bookwyrm/activitypub/verbs.py", line 99, in action
    self.to_model()
  File "/app/bookwyrm/activitypub/base_activity.py", line 126, in to_model
    field.set_field_from_activity(instance, self)
  File "/app/bookwyrm/models/fields.py", line 75, in set_field_from_activity
    formatted = self.field_from_activity(value)
  File "/app/bookwyrm/models/fields.py", line 145, in field_from_activity
    return activitypub.resolve_remote_id(value, model=related_model)
  File "/app/bookwyrm/activitypub/base_activity.py", line 256, in resolve_remote_id
    return result if not get_activity else result.to_activity_dataclass()
NameError: name 'get_activity' is not defined
```
The .env.example in production is back to the version without the `REDIS_ACTIVITY_HOST`. Does it work without or does it have to be set once?

Just realized that after this, nothing gets passed to flower anymore, I (un)followed and liked stuff from other Masto instances and bookwyrm.social. Restarted docker, but nothing happens.

I added the redis stuff to .env and then ran  `./bw-dev update`, `docker-compose build` and `docker-compose exec web python manage.py rebuild_feeds`. The latter returned `Unknown command: 'rebuild_feeds'`, but the feeds looked okay and the updating and rebuilding were successful. Then noticed the above mentioned errors. Removed the `REDIS_ACTIVITY_HOST` stuff and rebuilt but it still didn't work, nothing gets through to wyrms.de.

I went back to a snapshot I did before updating so everything works again but it looks like the update broke something (?).

**Comment by mouse-reeve** [comment]
dang, yes it definitely is in a bad state. I tried to update bookwyrm.social to the new redis activitystreams code and hit a port conflict, so I reverted the commit in `production` and I've been hotfixing the bug fixes for the last couple days. I didn't register how that would mess up other installs! sorry about that. I'll try that upgrade again and see if I can get b.s working on the production branch.

**Comment by mouse-reeve** [comment]
okay it turns out I had the silliest problem with my update (I didn't remove an orphan container which was stealing the port I needed). The production branch *should* be good to go with the new redis configuration. Sorry about that!

**Comment by tofuwabohu** [comment]
Hm, the rebuild_feeds thingy was found this time but crashed:
``` python
docker-compose exec web python manage.py rebuild_feeds
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 578, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/bookwyrm/management/commands/rebuild_feeds.py", line 38, in handle
    erase_feeds()
  File "/app/bookwyrm/management/commands/rebuild_feeds.py", line 17, in erase_feeds
    r.flushall()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1252, in flushall
    return self.execute_command('FLUSHALL', *args)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to redis_activity:6379. Temporary failure in name resolution.
```
The instance was up after I removed the orphaned container you mentioned, but I couldn't access the start page (Server error). Sorry 😬

**Comment by mouse-reeve** [comment]
hm, can you try commenting out the erase all command in `bookwyrm/management/commands/rebuild_feeds.py` on line 38? and, if the instance working at all, feeds aside?

**Comment by mouse-reeve** [comment]
I guess also try `docker-compose ps` and make sure that the right images are up (particular `redis_activity`)

**Comment by tofuwabohu** [comment]
`redis_activity` wasn't up, after starting it manually the rebuild_feeds worked (including the erase all)! The page is up and seems to work, but not I can't reach flower on :8888 (even though it's up under `docker-compose ps`). Also, trying to follow me from Masto doesnt' work (no notif and Masto waits for confirmation).

**Comment by mouse-reeve** [comment]
I had to stop and re-build flower -- if you check the logs for it, you should be able to see what redis host it's trying to connect to, if it's `redis` and not `redis_broker`, that's your problem and stopping and than bringing it back up with `--build` should fix it

**Comment by tofuwabohu** [comment]
Yeah, it's celery that can't connect to redis: `celery_worker_1   | [2021-03-25 20:39:35,899: ERROR/MainProcess] consumer: Cannot connect to redis://:**@redis:6379/0: Error -3 connecting to redis:6379. Temporary failure in name resolution..`

Since this was the problem we had when setting the instance up, I'm fiddling with all combinations of how to put PW and port into the celery settings in .env but no luck so far.

**Comment by mouse-reeve** [comment]
oh I see! in .env, `CELERY_BROKER` and `CELERY_RESULTS_BACKEND` need to be set to `redis://:${REDIS_BROKER_PASSWORD}@redis_broker:6379/0` -- the key thing is changing `@redis` to `@redis_broker`

**Comment by tofuwabohu** [comment]
Omg I should have seen that, sorry! Thanks. 🎊 Everything working smoothly now.
