### ISSUE TITLE
Instance blocklists

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#804]
**Is your feature request related to a problem? Please describe.**
As an admin, I'd like to specify instances that my instance won't federate with.

**Describe the solution you'd like**
The instance should not show any remote content of those instances and, as far as it's technically possible with AP, deny those instances access to users, posts, etc.

**Describe alternatives you've considered**
Possibly this can be done via nginx config? Idk.

**Additional context**

 It would be nice to have a user interface similar to the Mastodon one where one can adds notes on why instances are suspended. 
 
![image](https://user-images.githubusercontent.com/66644064/112718955-86d2e800-8ef6-11eb-956c-9ecee2771529.png)
![image](https://user-images.githubusercontent.com/66644064/112718985-ac5ff180-8ef6-11eb-83f0-1ba06c599a11.png)

Additionally, it would be nice to have a possibility to ex- and import blocklists, maybe in this format: https://fediblock.org/#api

**Comment by tastytea** [comment]
**Workaround**: Mastodon, Pleroma and Friendica send the URL of the instance as part of their User-Agent when they make requests. For example:

|  Software | User-Agent                                                     |
|----------:|:---------------------------------------------------------------|
|  Mastodon | http.rb/4.4.1 (Mastodon/3.3.0; +https://example.com/)          |
| Friendica | Friendica 'Red Hot Poker' 2021.03-rc-1412; https://example.com |
|   Pleroma | Pleroma 2.3.0; https://example.com <email@example.com>         |

You could make a file like this:

```nginx
map $http_user_agent $blockedagent {
    default 0;
    ~*example\.com 1;
}
```

include it in your nginx config (`include myfile;`) and then write this into your `server`-block:

```nginx
if ($blockedagent) {
    return 403;
}
```

**Comment by mouse-reeve** [comment]
I _think_ this should cover all the bases in terms of creating blocked servers and making sure they're really blocked, but federation is complicated so if you notice anything that seems fishy, let me know

**Comment by tofuwabohu** [comment]
Amazing! Will do some testing once it gets into production. :)
