### ISSUE TITLE
Number of followers of suggested users is wrong

### ISSUE THREAD

**Issue by bibliotechy** [mouse-reeve/bookwyrm#806]
**Describe the bug**
Recommendations for new users to follow in my feed appear with a number of followers we have in common, but that number looks off. The user recommendation I saw said they had 306 followers I follow, but neither of us has that many followers.

**To Reproduce**
1. Go to your home feed after logging in
3. Scroll down until you see a recommendation for a user to follow
4. See the weird follower count

**Expected behavior**
The number of mutual followers should be accurate 

**Screenshots**

Screenshot
![409385BB-8652-4B7C-9137-5B6CDB7F0866](https://user-images.githubusercontent.com/1128631/112738864-2ca94580-8f3d-11eb-92af-a86dc7148986.jpeg)

**Smartphone (please complete the following information):**
    - Device: iPhone 11
    - OS: 
    - Browser safari
    - Version

**Additional context**

**Comment by tofuwabohu** [comment]
The same person is suggested to me and also with 306 followers I follow. Plus someone else with 1722 followers.

**Comment by mouse-reeve** [comment]
this bug is _so_ funny to me, this is what I get for writing such a ridiculous query
