### ISSUE TITLE
HTML views should support microformats

### ISSUE THREAD

**Issue by bekopharm** [mouse-reeve/bookwyrm#84]
Consider adding [microformats](http://microformats.org/wiki/microformats2) to HTML views.

**Comment by jalcine** [comment]
Seconded! Using Microformats will:

- make it easy for most Web tools to both present and parse
- keep it extensible with a battle-tested format
- make it friendly to presenting in the poster's preferred way without having to create alternative formats to show the same thing.

**Comment by mouse-reeve** [comment]
thank you both for the suggestion! @jalcine can you clarify your third point? I'm not sure I understand that use case.

**Comment by jalcine** [comment]
With a Microformats parser, you can define something in HTML (mostly) anyway you'd want but still get useful structured information (similar to how one would parse JSON).

An example is my own personal site! 

https://jacky.wtf to https://ruby.microformats.io/microformats?utf8=%E2%9C%93&url=https%3A%2F%2Fjacky.wtf

**Comment by jalcine** [comment]
I'd be happy to brainstorm some ideas on how to define the static pages of fedireads with microformats with you!

**Comment by mouse-reeve** [comment]
I see, that example is super helpful, thank you! I took a look a while back and as I recall it seems like there are a lot of natural fits around serializing book data, so brainstorming would be greatly ppreciated

**Comment by bekopharm** [comment]
Mayhap I should have mentioned https://microformats.io/ too. It's probably a better example to get the idea.

**Comment by arkhi** [comment]
There are existing definitions for [structured data for books](https://schema.org/Book). Same goes for [Rating](https://schema.org/Rating), [Person](https://schema.org/Person), etc.

I can work on implementing this in the [book template](https://github.com/mouse-reeve/bookwyrm/blob/main/bookwyrm/templates/book/book.html) unless anybody has any objection. :)

**Comment by arkhi** [comment]
A useful browser addon to have is http://osds.openlinksw.com/.

**Comment by arkhi** [comment]
An interesting problem is with the [publisher property](https://schema.org/publisher) which needs to be either an Organization or a Person.

**Comment by mouse-reeve** [comment]
This would just be the `publishers` field that already exists in the book data, right?

**Comment by arkhi** [comment]
>This would just be the `publishers` field that already exists in the book data, right?

I saw an included template with publisher details and the name of the publisher; is the type (person or organisation) available too?

**Comment by mouse-reeve** [comment]
There's no additional metadata on that, I think it's safe to treat it as an organization.

**Comment by arkhi** [comment]
Same thing goes with _author_ which can more easily be one of both, I guess. :)

**Comment by arkhi** [comment]
Another potential issue might be the [bookformat](https://schema.org/bookFormat) property is limited to a list of values whereas the book edition is free text.

**Comment by bekopharm** [comment]
Schema is *not* microformats. You're mixing microdata and microformats hijacking this feature request.

Similar subject, different concept.

**Comment by arkhi** [comment]
Hello @bekopharm… I agree microdata is not the same as microformats.

I’m sorry that you felt I hijacked the current issue. The issue being stalled for almost a year, I didn’t feel like interrupting anyone’s conversation.

The issue does not specify why microformats should be implemented and I assumed it was to provide structured data to BookWyrm, which the microdata definitions present on schema.org allow to implement more precisely than microformats to my knowledge. Let me know if there are adverse consequences to the work I’ve done.

That’s on me; I can create a new issue and refrain from mentioning this Issue in the Future.

**Comment by bekopharm** [comment]
There are various use cases outlined above :shrug: 

I mean thanks for contributing I guess. That's always good. It's just a different thing.

**Comment by mouse-reeve** [comment]
@bekopharm This is not an acceptable way to talk to people here. If you have concerns or differences of opinion about work on this project, you need to raise them with courtesy and consideration of others; there's absolutely no call to respond rudely.

**Comment by bekopharm** [comment]
Wow. I'm really bewildered by your reply @mouse-reeve and a… rage close? So I asked a native speaker what might be the issue and was pointed out that "hijacking" may be the wrong wording implying terrorism when merely derailing was meant.

If it's just that I ask for forgiveness and blame the language barrier. There was no offence intended.

Otherwise I have seriously no idea what tripped you off :(

**Comment by mouse-reeve** [comment]
I'm really glad to hear that the tone was unintentional! It's important to me that folks know that their contributions are valued, and that we don't diminish each other's efforts. 

The ticket wasn't rage closed, I'm trying to keep on top of issues and have been closing and re-thinking many that are over a year old and haven't had much action, since the project has progressed a lot since then.
