### ISSUE TITLE
Book context missing in boosts from remote posts

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#858]
**Describe the bug**
In some cases, a post federates and the associated book is not shown.

**Screenshots**
Screenshot from a review where the associated book is not shown. It's a remote post and the booster is on another instance as well.
![image](https://user-images.githubusercontent.com/66644064/113485135-74cfe700-94ac-11eb-9217-cfa510bb52e2.png)

Screenshot from the original instance with the book
![image](https://user-images.githubusercontent.com/66644064/113485156-992bc380-94ac-11eb-93c0-eb9a3b8ccc09.png)

Screenshots from the federated tl where the remote review is there once with book, once without.
![image](https://user-images.githubusercontent.com/66644064/113485238-d6905100-94ac-11eb-99ff-d64f84c6133e.png)

**Additional context**
Will post more matching posts. In other cases, it works properly - it may be that it works if the OP is followed from my instance so the post is already known but not enough examples yet.

**Comment by mouse-reeve** [comment]
That's not good! It looks like boosted are being received in "pure" mode intended for non-bookwyrm services, which could be a problem on either side of the transaction. I'll look further.
