### ISSUE TITLE
Redis error when fetching feeds

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#868]
I'm currently running 7b3c85f351b5331d74bb1c5ab4d5116ad82bc78d outside Docker.

When opening a logged-in user's main page, I get a request response error for Redis: WRONGTYPE Operation against a key holding the wrong kind of value.

The error is the same when trying to run *populate_streams* (also displayed as *populate_feeds* in *bw-dev*).

If it helps, I think this is to do with a recent data type change, though I wasn't able to do bisects yet due to migrations.

**Comment by mouse-reeve** [comment]
yes, sorry about that! I had to switch from using redis lists to ordered sets, which means you have to erase the existing activity streams and re-build new ones. It should fix it to run:
``` bash
docker-compose exec web python manage.py erase_streams
docker-compose exec web python manage.py populate_streams
```

Is that doesn't fix it let me know!

**Comment by Flameborn** [comment]
That did it, thank you very much!

*python manage.py erase_streams* and *python manage.py populate_streams* did the trick.
