### ISSUE TITLE
Can't create Invites

### ISSUE THREAD

**Issue by tofuwabohu** [mouse-reeve/bookwyrm#877]
**Describe the bug**
When creating a new invite, the following appears:
![screenshot that says ERRORS: invitees - This field is required](https://user-images.githubusercontent.com/66644064/113598361-4f261780-963d-11eb-96b4-6f712cc4d8fe.png)
Rest of the page is blank.

It appeared since the last update I did a few days ago (don't know at which commit exactly, sorry) and didn't change with the last one.

**Additional context**
It doesn't matter what I set for Expiry and Use limit.
Also, there's an invite in the list that has "Max uses: None" that I'm not sure where it comes from.

**Comment by mouse-reeve** [comment]
oh I know exactly how I broke this! should be a simple fix, just a sec
