### ISSUE TITLE
Timeout for lists

### ISSUE THREAD

**Issue by bytesnake** [mouse-reeve/bookwyrm#885]
I'm looking for an alternative to goodreads and really like your project goals :) Not sure whether this is the right place to report for the main instance as well.

**Describe the bug**
I'm trying to view a list at the `bookwyrm.social` pod, but getting a timeout for any list number. The nginx server throws a bad gateway error.

**To Reproduce**
1. Go to https://bookwyrm.social/list/27
2. See `504 Bad Gateway`

**Expected behavior**
See a beautiful list of awesome books

**Desktop (please complete the following information):**
    - OS: Archlinux 5.10.8-arch1-1
    - Browser Firefox
    - Version 84.0.2

**Comment by mouse-reeve** [comment]
hm, I was just able to open it normally, and that's usually a transient error -- are you still seeing the 502 or are things loading? I'll take a look at the logs and see if I can find anything

**Comment by bytesnake** [comment]
ups I meant `504 Gateway timeout` of course :smile: it should not be user specific if it's caused by the nginx server. Here are request and answer:

```
GET /list/27 HTTP/2
Host: bookwyrm.social
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: csrftoken=***
sessionid=***
Upgrade-Insecure-Requests: 1
```

```
HTTP/2 504 Gateway Timeout
server: nginx/1.19.2
date: Tue, 06 Apr 2021 14:20:27 GMT
content-type: text/html
content-length: 167
X-Firefox-Spdy: h2
```

**Comment by mouse-reeve** [comment]
hm, it does look like there was a big cpu and load spike around that time, and the web worker got overloaded and timed out. Probably unrelated to that list page, which is pretty low-weight. Are things looking normal now? The load has been back to a usual level for a while now

**Comment by bytesnake** [comment]
yes started to work again ~3min ago
