### ISSUE TITLE
“Go to my profile”-button doesn't take me to my profile when I'm on another profile

### ISSUE THREAD

**Issue by tastytea** [mouse-reeve/bookwyrm#889]
**Describe the bug**
When I look at the profile of a user, the hyperlink around my username in the top-right points to the profile page I'm on.

**To Reproduce**
1. Go to a [profile page that is not yours](https://bookwyrm.social/user/tastytea)
2. Click on your username in the top-right
3. It links to the profile page you're already on.

**Expected behavior**
It takes me to my profile page.

**Additional context**
HTML snippet:
```html
<div class="navbar-item has-dropdown is-hoverable">
                <a href="/user/mouse" class="navbar-link pulldown-menu" role="button" aria-expanded="false" tabindex="0" aria-haspopup="true" aria-controls="navbar-dropdown">
                    
<img class="avatar image is-32x32" src="/images/avatars/6ac6b598-a1e1-4496-b5ca-daf8564e82ac.png" alt="avatar for tastytea">
```

**Comment by tofuwabohu** [comment]
I think I can fix this, give me a sec
