### ISSUE TITLE
the "first published date" and "published date" fields aren't saved when creating a book

### ISSUE THREAD

**Issue by void-witch** [mouse-reeve/bookwyrm#894]
**Describe the bug**
creating a new book with the required fields creates a book with everything saved *except* for the published date fields. editing the new book saves the fields

**To Reproduce**
1. Go to `/create-book`
2. enter in a book name, and a "first published date"
3. submit the form
4. see that the form on the confirmation screen doesn't have the date filled
5. confirm
6. click the edit button on the new book
7. see that the book has no date
8. (optionally) add a date and submit, then confirm the date has been saved

**Expected behavior**
the book is saved, along with the published dates

**Desktop (please complete the following information):**
    - OS: fedora 33 x64
    - Browser firefox
    - Version 87.0

**Additional context**
the template for confirming creating a new book expects the initial field value in the `book` attribute, but the initial data is actually in the `form` attribute

**Comment by void-witch** [comment]
closed in #893

**Comment by void-witch** [comment]
actually, should we keep this open until a regression test is written just to be safe? @mouse-reeve

**Comment by mouse-reeve** [comment]
yeah, I suppose that's the responsible choice :)

**Comment by void-witch** [comment]
i got a regression test that fails and succeeds in the right places. unfortunately, it relies on checking that the rendered html contains `<input type="date" name="first_published_date" class="input" id="id_first_published_date" value="[date]">`. i feel like that couples the test to closely to the html, but i genuinely can't think of another way since the only time this bug appears is during the template rendering

if anyone has a better way i'd be more than happy to hear it, but unfortunately i think this is the best we have for now :p
