### ISSUE TITLE
Spoiler-free/book club-enabling comments and reviews?

### ISSUE THREAD

**Issue by vitorio** [mouse-reeve/bookwyrm#99]
Following up from a recent newsletter, which writes:

> I'm working on adding granular post privacy controls, so you can choose to keep your data private to just yourself, only shared with your friends, local to your instance, or available to the public.

If comments and reviews can be managed more granularly (#98), being able to only view and reply to comments made _up to the point I've read in the book_ would support spoiler-free, asynchronous participation in a reading event.

**Comment by mouse-reeve** [comment]
I think now that comments on a book can have both content warnings and be tagged with where in the book they are, this effectively fixed!
